# -*- coding: utf-8 -*-
"""The goal pipeline class."""

from copy import deepcopy
from typing import AsyncGenerator, Literal

from pydantic import BaseModel, Field

from .._logging import logger
from ..types import ReplyFinishedReason
from ..agent import Agent
from ..message import UserMsg, Msg, TextBlock, DataBlock
from ..event import (
    UserConfirmResultEvent,
    ExternalExecutionResultEvent,
    RequireExternalExecutionEvent,
    RequireUserConfirmEvent,
    UserInterruptEvent,
)


class _ExecutionReport(BaseModel):
    """The output of an execution."""

    report: str = Field(
        description=(
            "An achievement report of the given goal. E.g. file paths, entry "
            "points, how-to-run, runtime environment, etc. "
            "So that a verifier can check if you have achieved the goal. "
        ),
    )


class _VerificationResult(BaseModel):
    """The result of a verification."""

    result: Literal["pass", "fail", "impossible"] = Field(
        description=(
            "The verfication result, which can be 'pass', 'fail', or "
            "'impossible'. 'impossible' means the given goal is impossible to "
            "achieve, and the executor should stop trying."
        ),
    )

    message: str = Field(
        description=(
            "If not passed, the message should explain why it "
            "failed, and what needs to be fixed. List the specific "
            "issues that need to be addressed, including where to "
            "exactly find them (e.g., file paths, line numbers)."
        ),
    )


class GoalPipeline:
    """The goal pipeline class that run an executor and verifier in a loop
    until the goal is achieved."""

    def __init__(
        self,
        executor: Agent,
        verifier: Agent,
        verifier_reset_context: bool = True,
        max_iters: int = 10,
        max_retries: int = 3,
    ) -> None:
        """Initialize the goal pipeline.

        Args:
            executor (`Agent`):
                The executor agent that performs the work.
            verifier (`Agent`):
                The verifier agent that checks the goal achievement.
            verifier_reset_context (`bool`, optional):
                Whether to reset the verifier's context after each iteration.
                Defaults to `True`.
            max_iters (`int`, optional):
                The maximum number of goal achievement attempts.
            max_retries (`int`, optional):
                The maximum number of retries for the executor and verifier
                agents to generate valid structured outputs. Defaults to `3`.
        """
        self.executor = executor
        self.verifier = verifier
        self.verifier_reset_context = verifier_reset_context
        self.max_iters = max_iters
        self.max_retries = max_retries
        # Rounds already judged. On the instance rather than in
        # ``reply_stream``, so a HITL resume does not restart the budget.
        self._iters = 0
        self._goal: None | list[TextBlock | DataBlock] = None

    async def reply_stream(
        self,
        inputs: Msg
        | list[Msg]
        | UserConfirmResultEvent
        | UserInterruptEvent
        | ExternalExecutionResultEvent,
    ) -> AsyncGenerator:
        """Run the goal pipeline.

        Args:
            inputs (`Msg | list[Msg] | UserConfirmResultEvent | \
            UserInterruptEvent | ExternalExecutionResultEvent`):
                The inputs to the pipeline, which can be a message, a list of
                messages, a user confirmation result event, a user interrupt
                event, or an external execution result event.

        Yields:
            `AgentEvent`:
                The events generated by the executor and verifier agents
                during the pipeline execution.
        """

        # Prepare inputs for executor and verifier
        executor_inputs, verifier_inputs = None, None
        if (
            isinstance(inputs, Msg)
            or isinstance(inputs, list)
            and all(isinstance(_, Msg) for _ in inputs)
        ):
            executor_inputs = deepcopy(inputs)
            # A fresh run, so the iteration budget starts over.
            self._iters = 0

            hint = (
                "<system-reminder>When you finish the goal, you should "
                "summarize your output (if any) so that a verifier can check "
                "whether you have achieved the goal (e.g., file paths, entry "
                "points, how-to-run, runtime environment, etc.)."
                "</system-reminder>"
            )

            if isinstance(inputs, Msg):
                self._goal = inputs.content
                executor_inputs.content.append(TextBlock(text=hint))
            else:
                self._goal = []
                for _ in inputs:
                    self._goal.extend(_.content)
                executor_inputs.append(
                    UserMsg("system", content=hint),
                )

        elif isinstance(
            inputs,
            (
                UserConfirmResultEvent,
                UserInterruptEvent,
                ExternalExecutionResultEvent,
            ),
        ):
            if inputs.reply_id == self.executor.state.reply_id:
                executor_inputs = inputs
            elif inputs.reply_id == self.verifier.state.reply_id:
                verifier_inputs = inputs
            else:
                raise ValueError(
                    f"Invalid inputs with reply_id: {inputs.reply_id}. ",
                )

        if isinstance(inputs, UserInterruptEvent):
            parked = (
                self.verifier if verifier_inputs is not None else self.executor
            )
            async for _ in parked.reply_stream(inputs=inputs):
                yield _
            return

        # Start the pipeline loop
        while True:
            # Executor step
            break_loop = False
            execution_report = None
            if executor_inputs is not None:
                while execution_report is None:
                    # Run the executor with the given inputs
                    async for _ in self.executor.reply_stream(
                        inputs=executor_inputs,
                        structured_schema=_ExecutionReport,
                        yield_final_msg=True,
                    ):
                        yield _
                        if isinstance(
                            _,
                            (
                                RequireExternalExecutionEvent,
                                RequireUserConfirmEvent,
                            ),
                        ):
                            break_loop = True
                        elif (
                            isinstance(_, Msg)
                            and _.finished_reason
                            == ReplyFinishedReason.COMPLETED
                            and _.structured_output
                        ):
                            execution_report = _.structured_output.get(
                                "report",
                            )

                    if break_loop:
                        # Break the loop for hitl events
                        break

                    if execution_report is None:
                        # Update the instruction
                        executor_inputs = UserMsg(
                            name="system",
                            content=(
                                "<system-reminder>You have failed to generate "
                                "valid execution report. You should call the "
                                "'GenerateStructuredOutput' tool with a valid "
                                "structured output that matches the schema. "
                            ),
                        )

            if break_loop:
                # The executor parked, so there is nothing to verify yet.
                break

            # Verifier
            final_msg = None
            instruction = verifier_inputs or UserMsg(
                name="user",
                content=[
                    TextBlock(
                        text=(
                            "<system-reminder>Now you should verify the work "
                            "done by the executor. "
                            "The goal is as follows, you should "
                            "verify whether the executor has "
                            "achieved the goal.\n<goal>"
                        ),
                    ),
                    *(self._goal or []),
                    TextBlock(
                        text=(
                            "</goal>\nThe executor's achievement report is as "
                            f"follows:\n<report>{execution_report}</report>"
                            "</system-reminder>"
                        ),
                    ),
                ],
            )
            verifier_inputs = None
            while final_msg is None:
                async for _ in self.verifier.reply_stream(
                    inputs=instruction,
                    structured_schema=_VerificationResult,
                    yield_final_msg=True,
                ):
                    if (
                        isinstance(_, Msg)
                        and _.finished_reason == ReplyFinishedReason.COMPLETED
                    ):
                        final_msg = _
                    elif isinstance(
                        _,
                        (
                            RequireExternalExecutionEvent,
                            RequireUserConfirmEvent,
                        ),
                    ):
                        break_loop = True
                        yield _
                    else:
                        yield _

                if break_loop:
                    # Escape the loop for hitl events
                    break
                if final_msg is None:
                    continue
                if final_msg.structured_output is None:
                    # Update the instruction for valid verification result
                    # TODO: support multimodal verification instruction
                    final_msg = None
                    instruction = UserMsg(
                        name="system",
                        content=(
                            "<system-reminder>You have failed to "
                            "generate valid verification result. "
                            "You should call the "
                            "'GenerateStructuredOutput' tool with "
                            "a valid structured output that matches "
                            "the schema. Recall the verification "
                            "requirements as follows:\n"
                            f"{self._goal}</system-reminder>"
                        ),
                    )
                elif final_msg.structured_output.get("result") in (
                    "pass",
                    "impossible",
                ):
                    if final_msg.structured_output["result"] == "impossible":
                        logger.info(
                            "The verifier judged the goal impossible: %s",
                            final_msg.structured_output.get("message"),
                        )
                    # Settled either way, so the loop ends here.
                    break_loop = True
                else:
                    self._iters += 1
                    if self._iters >= self.max_iters:
                        # Out of attempts; the work never passed
                        break_loop = True
                        break

                    # Feedback to the executor for further improvement
                    feedback = final_msg.structured_output.get("message")
                    executor_inputs = UserMsg(
                        name="system",
                        content=(
                            "<system-reminder>You've failed to pass the "
                            "verification. Now recorrect your work based on "
                            f"the following feedback:\n{feedback}"
                            "</system-reminder>"
                        ),
                    )

            if break_loop:
                # Break the loop for hitl events or verification passed
                break
